
routes:

    "/bar":
        hooks: [ test ]
        
    "/foo":
        hooks: [ test, bugs ]
        config:
            test:
                foo: bar
                baz: quux

            bugs:
                some: value
config:
    test:
        prop: global value for test hook

    bugs:
        another: global property for bugs hook